#import random module

import random

#define a welcome function to welcome user by name

def welcome():
    user_name=input("What is your game name?: ").capitalize()

    if user_name.isalpha():
        print("Hi", user_name,"! We're glad to have you here today :) \n You will have 6 attempts to correctly guess letters in the word, which will be generated by a computer.")

    else:
        print("Please enter a name using only letters.")
        user_name=input("What is your game name?: ").capitalize()
        print("Hi", user_name,"! We're glad to have you here today :) \n You will have 6 attempts to correctly guess letters in the word, which will be generated by a computer.")

#define function asking the user if the want to play again

def play_again():
    user_response = input("Would you like to play the game again? Enter \"y\" or \"n\" : ").lower()

    if user_response == "y":
        run_game()
    elif user_response == "n":
        print("See you next time!")
    else:
        print("invalid input")
        user_response = input("Would you like to play the game again? Enter \"y\" or \"n\" : ").lower()

#Define function for generating the random word that will be guessed by the user

def random_word():
    words = ["boat","dog","house","store","snake","apple","peanut","dinner","woman","idea","product","chest","bread","wedding","oven","bath","road","wife","man","injury","bonus","phone","boyfriend","friend","boy","girl","menu","stranger","world","death","king","queen","army","actor","river","song","basket","cat","tooth","pizza","uncle","aunt","studio","client"]
    return random.choice(words).lower()

#define function to run the game

def run_game():
    welcome()
    alphabet = "abcdefghijklmnopqrstuvwxyz7"
    game_word= random_word()
    user_guesses=[]
    user_tries = 7
    guessed = False
    print("")
    print("There are", len(game_word),"letters in the word and it is a noun.")

#While loop is created to allow the user to continue guessing

#For when the user attempts to guess a single letter
    while guessed == False and user_tries > 0:
        print("You have", str(user_tries), "tries remaining.")
        guess = input("Guess a letter in the word, or if you feel confident, guess the whole word.\nTo view letters that you already guessed, enter \"7\":").lower()
        if len(guess)== 1:
            if guess == "7":
                print(user_guesses)
            elif guess not in alphabet:
                print("That is an invalid input. Please enter letters only.")
            elif guess in user_guesses:
                print("You have already tried that letter.")
            elif guess not in game_word:
                print("Sorry, that letter is not in the word.")
                user_guesses.append(guess)
                user_tries-=1
            elif guess in game_word:
                print("Excellent! You correctly guessed a letter!")
                user_guesses.append(guess)
            else:
                print("Invalid input. Try again.")

      #For when the user attempts to guess the whole word

        elif len(guess) == len(game_word):
            if guess == game_word:
                print("Wow! You're Good! You correctly guessed the entire word.")
                guessed=True
            else:
                print("Sorry, that's not the right word.")

                user_tries-=1

        #For when the user enters the wrong amount of letters for the word. For example, if they enter 5 letters for a 4 letter word.
        else:
            print("The length of your guess should either be 1 letter or the length of the word")
            user_tries-=1

        status= ""
        if guessed == False:
            for letter in game_word:
                if letter in user_guesses:
                    status += letter
                else:
                    status += '_'
            print(status)

        if status == game_word:
            print("Awesome job! You correctly guessed the word!")
            guessed == True
            break
        elif user_tries == 0:
            print('''  +---+
  |   |
  O   |
 /|\  |
 / \  |
      |
=========''')
            print("You've exhausted all of your tries without guessing the word! :( The correct word was", game_word.capitalize())
            break

        elif user_tries==6:
            print('''+---+
|   |
    |
    |
    |
    |
=========''')
        elif user_tries==5:
            print( '''+---+
|   |
O   |
    |
    |
    |
=========''')
        elif user_tries==4:
            print('''+---+
|   |
O   |
|   |
    |
    |
=========''')
        elif user_tries==3:
            print(''' +---+
 |   |
 O   |
/|   |
     |
     |
=========''')
        elif user_tries==2:
            print('''+---+
 |   |
 O   |
/|\  |
     |
     |
=========''')

        elif user_tries==1:
            print('''+---+
 |   |
 O   |
/|\  |
/    |
     |
=========''')
        elif user_tries==0:
            print('''  +---+
 |   |
 O   |
/|\  |
/ \  |
     |
=========''')

    play_again()
run_game()

